[package]
name = "auto-testing"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
bebop = { path = "../../../Runtime/Rust" }

[build-dependencies]
bebop-tools = { path = "../../../Tools/cargo", default-features = false, features = ["format"] }
