[package]
name = "bebop-handler-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "1.0", features = ["full", "parsing", "printing"] }
quote = "1.0"
proc-macro2 = "1.0"

[lib]
proc-macro = true
