[package]
name = "functionality-testing"
version = "0.1.0"
edition = "2018"

[lib]

[dependencies]
bebop = { path = "../../../Runtime/Rust" }
bitflags = "1.3.2"

[build-dependencies]
bebop-tools = { path = "../../../Tools/cargo", default-features = false }
