[package]
name = "bebop"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[features]
# where reasonable, skip decoding checks, this will cause random issues if invalid UTF8 is sent to
# the program
unchecked = []
# Enable this feature to use in a buildscript. Prevents building all other code and includes code
# for use in cargo build scripts.
cargo = []
