[package]
name = "manual-testing"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
bebop = { path = "../../../Runtime/Rust", default-features = false }

[features]
default = ["bebop-owned-all"]
bebop-owned-all = []