name: bebopc
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-compiler:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: macos-latest
            CONFIGURATION: macOS-Release
            RUNTIME: osx-x64
            ARTIFACT: bebopc

          - os: windows-latest
            CONFIGURATION: Windows-Release
            RUNTIME: win-x64
            ARTIFACT: bebopc.exe

          - os: ubuntu-latest
            CONFIGURATION: Linux-Release
            RUNTIME: linux-x64
            ARTIFACT: bebopc
    steps:
      - uses: actions/checkout@v1

      - name: Get Enviorment Variables
        id: dotenv
        uses: falti/dotenv-action@v0.2.5

      - name: Install Dependencies
        if: ${{matrix.os}} == 'ubuntu-latest'
        run: sudo apt-get install clang zlib1g-dev libkrb5-dev=1.16 libtinfo5

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x" # SDK Version to use; x will use the latest version of the 5.0 channel
      - name: Restore Solution
        run: dotnet restore
      - name: Build bebopc
        run: dotnet publish -c ${{matrix.CONFIGURATION}} -r ${{matrix.RUNTIME}} -p:ReleaseVersion=${{ steps.dotenv.outputs.version }}
        working-directory: ./Compiler/

      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.RUNTIME}}
          path: ./bin/compiler/${{matrix.CONFIGURATION}}/publish/${{matrix.ARTIFACT}}

  build-tools:
    env:
      TOOLS_ROOT: ${{github.workspace}}/Tools/C#
      TOOLS_PATH: ${{github.workspace}}/Tools/C#/tools
      WINDOWS_ARTIFACT: win-x64
      MAC_ARTIFACT: osx-x64
      LINUX_ARTIFACT: linux-latest
    needs: build-compiler
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get Enviorment Variables
        id: dotenv
        uses: falti/dotenv-action@v0.2.5

      - name: Download Windows Build
        uses: actions/download-artifact@v2
        with:
          name: ${{env.WINDOWS_ARTIFACT}}
          path: ${{env.TOOLS_PATH}}/windows/

      - name: Download macOS Build
        uses: actions/download-artifact@v2
        with:
          name: ${{env.MAC_ARTIFACT}}
          path: ${{env.TOOLS_PATH}}/macos/

      - name: Download Linux Build
        uses: actions/download-artifact@v2
        with:
          name: ${{env.LINUX_ARTIFACT}}
          path: ${{env.TOOLS_PATH}}/linux/

      - name: Build bebop-tools NuGet Package
        run: call ${{env.TOOLS_ROOT}}/build.cmd ${{ steps.dotenv.outputs.version }}
        shell: cmd
        working-directory: ${{env.TOOLS_ROOT}}

      - name: Upload bebop-tools Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bebop-tools-latest
          path: ${{env.TOOLS_ROOT}}/packages/
