name: Bebop WebAssembly REPL
on:
  workflow_dispatch:
  push:
    paths:
      - "Repl/**"
  pull_request:
    paths:
      - "Repl/**"
jobs:
  build-repl:
    env:
      REPL_ROOT: ${{github.workspace}}/Repl
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Get Enviorment Variables
        id: dotenv
        uses: falti/dotenv-action@v1.0.4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
          dotnet-quality: 'preview'
      - name: Restore Project
        run: dotnet restore
        working-directory: ${{env.REPL_ROOT}}
      - name: Build REPL
        run: dotnet publish -c Release -p:ReleaseVersion=${{ steps.dotenv.outputs.version }}
        working-directory: ${{env.REPL_ROOT}}

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: bebop-repl-latest
          path: ${{github.workspace}}/bin/repl/Release/publish/wwwroot/
