name: Integration Tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - test-action-new-cli
  pull_request:
jobs:
  integration-tests:
    env:
      TEST_ROOT: ${{github.workspace}}/Laboratory/Integration
      RUNTIME_ROOT: ${{github.workspace}}/Runtime/C#
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            5.0.x
            6.0.x
            7.0.x
          include-prerelease: true
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.16.0" # LTS
      - name: Setup C++
        run: |
          sudo apt update
          sudo apt install gcc g++
      - name: Build Typescript runtime
        run: |
          yarn install
          yarn test
          yarn build
        working-directory: ./Runtime/TypeScript
      - name: Install python runtime
        run: pip install python-bebop
      - name: yarn install
        run: yarn install
        working-directory: ${{env.TEST_ROOT}}
      - name: Test
        run: node run_test.js
        working-directory: ${{env.TEST_ROOT}}
