name: Test Rust
on:
  push:
    branches:
      - master
      - test-action-new-cli
  pull_request:
jobs:
  test-rust:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Runtime Tests
        run: cargo test
        working-directory: ./Runtime/Rust
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.410"
      - name: Build Compiler
        run: |
          dotnet build Compiler
      - name: Generator Compiliation Tests
        run: cargo check -p auto-testing
        working-directory: ./Laboratory/Rust
      - name: Generator Funcunality Tests
        run: cargo test -p functionality-testing
        working-directory: ./Laboratory/Rust
