name: Test Rust
on:
  push:
    branches:
      - master
      - test-action-new-cli
  pull_request:
jobs:
  test-rust:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Runtime Tests
        run: cargo test
        working-directory: ./Runtime/Rust
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # SDK Version to use; x will use the latest version of the 5.0 channel
      - name: Build Compiler
        run: |
          dotnet build Compiler
          mv bin/compiler/Debug bin/compiler/Linux-Debug
      - name: Generator Compiliation Tests
        run: cargo check -p auto-testing
        working-directory: ./Laboratory/Rust
      - name: Generator Funcunality Tests
        run: cargo test -p functionality-testing
        working-directory: ./Laboratory/Rust
