name: Test Dart
on:
  push:
    branches:
      - master
      - test-action-new-cli
  pull_request:
jobs:
  test-dart:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.410" # SDK Version to use; x will use the latest version of the 7.0 channel
      - name: Build and run tests
        run: |
          mkdir gen
          grep dotnet test.sh | bash
          dart pub get
          dart pub run test
        working-directory: ./Laboratory/Dart
