name: Test TypeScript
on:
  push:
    branches:
      - master
      - test-action-new-cli
  pull_request:
jobs:
  test-typescript:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "18.16.0" # LTS
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x" # SDK Version to use; x will use the latest version of the 7.0 channel
          include-prerelease: true
      - name: Build and run tests
        run: |
          npm install
          bash compile-schemas.sh
          npm run test
        working-directory: ./Laboratory/TypeScript
