name: Test C#
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-csharp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.410
            9.0.300
      - name: Build and run tests
        shell: bash
        run: |
          dotnet run --project ../../Compiler/ --trace -i $(ls -p ../Schemas/Valid/*.bop | tr '\n' ' ') build -g "cs:./GeneratedTestCode/Output.g.cs,namespace=Bebop.Codegen"
          dotnet test -nowarn:CS0618
        working-directory: "./Laboratory/C#"
