name: Test C#
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-csharp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            5.0.x
            6.0.x
            7.0.x
          include-prerelease: true
      - name: Build and run tests
        shell: bash
        run: |
          dotnet run --project ../../Compiler/ --cs "./GeneratedTestCode/Output.g.cs" --namespace Bebop.Codegen --files $(ls -p ../Schemas/Valid/*.bop | tr '\n' ' ')
          dotnet test -nowarn:CS0618
        working-directory: "./Laboratory/C#"
